{"name": "test_01_Normal", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'access_token' in {'code': 40001, 'debug': {'class': 'Symfony\\\\Component\\\\HttpKernel\\\\Exception\\\\HttpException', 'file': '/home/webmaste...Route->runController()', ...]}, 'message': 'The username or password you’ve entered is incorrect.', 'status_code': 200}\n +  where {'code': 40001, 'debug': {'class': 'Symfony\\\\Component\\\\HttpKernel\\\\Exception\\\\HttpException', 'file': '/home/webmaste...Route->runController()', ...]}, 'message': 'The username or password you’ve entered is incorrect.', 'status_code': 200} = <bound method Response.json of <Response [200]>>()\n +    where <bound method Response.json of <Response [200]>> = <Response [200]>.json", "trace": "self = <test_001_gettoken.TestGetToken object at 0x000001F9D1096048>\n\n    @pytest.mark.level_1\n    def test_01_Normal(self):\n        '''用户名，密码正确'''\n        data = {\n            \"username\": \"test1\",\n            \"password\": \"Lb123456\",\n            \"language\": \"en\",\n            \"platform\": \"web\"\n        }\n        Log().info(\"%s.%s\" %(self.__class__.__name__,get_current_function_name()) +\"     ***Test Start***\")\n        r = webrequests().post(url=_url, data=data, headers=_header)\n    \n        try:\n    \n            assert r[0] == 200\n>           assert 'access_token' in r[1].json()\nE           AssertionError: assert 'access_token' in {'code': 40001, 'debug': {'class': 'Symfony\\\\Component\\\\HttpKernel\\\\Exception\\\\HttpException', 'file': '/home/webmaste...Route->runController()', ...]}, 'message': 'The username or password you’ve entered is incorrect.', 'status_code': 200}\nE            +  where {'code': 40001, 'debug': {'class': 'Symfony\\\\Component\\\\HttpKernel\\\\Exception\\\\HttpException', 'file': '/home/webmaste...Route->runController()', ...]}, 'message': 'The username or password you’ve entered is incorrect.', 'status_code': 200} = <bound method Response.json of <Response [200]>>()\nE            +    where <bound method Response.json of <Response [200]>> = <Response [200]>.json\n\nlifebyte_new_crm\\test_001_gettoken.py:38: AssertionError"}, "description": "用户名，密码正确", "attachments": [{"name": "log", "source": "8cf17a7c-d082-428f-8295-4706c88c1f88-attachment.txt", "type": "text/plain"}], "start": 1573034556681, "stop": 1573034556822, "uuid": "6b730a61-9b7e-4c7a-89f2-a2f590647e1e", "historyId": "4b53da55827612f4e164b8191297a219", "fullName": "lifebyte_new_crm.test_001_gettoken.TestGetToken#test_01_Normal", "labels": [{"name": "tag", "value": "level_1"}, {"name": "parentSuite", "value": "lifebyte_new_crm"}, {"name": "suite", "value": "test_001_gettoken"}, {"name": "subSuite", "value": "TestGetToken"}, {"name": "host", "value": "DESKTOP-iunu"}, {"name": "thread", "value": "20724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "lifebyte_new_crm.test_001_gettoken"}]}